// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXEBPg7AUBkOflRU_Owj-_kqMqEQ4fHqo',
    appId: '1:811661006478:web:a449cadafeed659e905bdf',
    messagingSenderId: '811661006478',
    projectId: 'fir-login-test-9f4fb',
    authDomain: 'fir-login-test-9f4fb.firebaseapp.com',
    storageBucket: 'fir-login-test-9f4fb.firebasestorage.app',
    measurementId: 'G-H8LGC1XKK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWktpk0H41c0Hk3Wh9fpxJ7kCfSAbbTY8',
    appId: '1:811661006478:android:03b9b2e147ced17b905bdf',
    messagingSenderId: '811661006478',
    projectId: 'fir-login-test-9f4fb',
    storageBucket: 'fir-login-test-9f4fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD140eLwetP9kkHMo-7yIjc0U8hxVAjRXY',
    appId: '1:811661006478:ios:7ea06534bab9ac58905bdf',
    messagingSenderId: '811661006478',
    projectId: 'fir-login-test-9f4fb',
    storageBucket: 'fir-login-test-9f4fb.firebasestorage.app',
    iosBundleId: 'com.example.firebaseLoginTest',
  );
}
